run_id:
  "S7-0007-484"

ubam:
  "nomatch_rawlib.basecaller.bam"

sample_info_csv:
  "sample_info.csv"

default_barcodes:
  "configs/barcodes.tsv"

barcode:
  "configs/barcodes.tsv"

ref_modi:
  # path/to/reference/gDNA.fasta
  sequence: "/media/hd1/jkim/genome/ABL1_NM005157.4/assembly/ucsc/hg19/NM_005157_exons_4_to_7.fa"
  fai: "/media/hd1/jkim/genome/ABL1_NM005157.4/assembly/ucsc/hg19/NM_005157_exons_4_to_7.fa.fai"
  path: "/media/hd1/jkim/genome/ABL1_NM005157.4/assembly/ucsc/hg19/"
  # path/to/bwa/index/directory
  #  index:          "/media/hd1/jkim/genome/ABL1_NM005157.4/index/ucsc/hg19/bwa/NM_005157_exons_4_to_7.fa"
  index: "/media/hd1/jkim/genome/ABL1_NM005157.4/index/ucsc/hg19/bwa/NM_005157_exons_4_to_7.fa"
  #  bowtie2_index:         "/media/hd1/jkim/genome/ABL1_NM005157.4/index/ucsc/hg19/bowtie2/NM_005157_exons_4_to_7"
  # path/to/gtf/file/with/transcripts.gtf
  annotation: "/media/hd1/jkim/genome/ABL1_NM005157.4/annotation/ucsc/refgene_hg19/refGene_3-1-2020.txt"
  star_index: "/media/hd1/jkim/genome/index/ucsc/hg19/star"

ref_full:
  sequence: "/media/hd1/jkim/genome/assembly/ucsc/hg19/hg19.fa"
  fai: "/media/hd1/jkim/genome/assembly/ucsc/hg19/hg19.fa.fai"
  # path/to/bwa/index/directory
  index: "/media/hd1/jkim/genome/index/ucsc/hg19/bwa/hg19"
  # path/to/gtf/file/with/transcripts.gtf
  annotation: "/media/hd1/jkim/genome/annotation/ucsc/refgene_hg19/refGene_3-1-2020.txt"

bwa:
  "/home/jaykim/jkim/singularity/bwa_v0.7.17_cv1.sif"
#  "/usr/local/bin/bwa"

samtools:
  "/home/jaykim/jkim/singularity/samtools_1.15.1--h1170115_0.sif"

fastqc:
  "/home/jaykim/jkim/singularity/fastqc_v0.11.9_cv8.sif"

multiqc:
  "/home/jaykim/jkim/singularity/multiqc_1.12--pyhdfd78af_0.sif"

cutadapt:
  "/home/jaykim/jkim/singularity/cutadapt_4.1--py38hbff2b2d_1.sif"

picard:
  "/usr/local/bin/picard.jar"

gatk4:
  "/home/jaykim/jkim/singularity/gatk4_4.2.4.0--hdfd78af_0.sif"

fastq_screen:
  path: "/home/jaykim/jkim/tools/FastQ-Screen-0.15.2/fastq_screen"
  conf: "/home/jaykim/jkim/tools/FastQ-Screen-0.15.2/FastQ_Screen_Genomes/fastq_screen.conf"
  sif: "/home/jaykim/jkim/singularity/fastq-screen-0.14.0.sif"

star:
  "/home/jaykim/jkim/singularity/star_2.7.10a--h9ee0642_0.sif"

bowtie2:
  path: "/usr/local/bin/bowtie2"

bcftools:
  "/home/jaykim/jkim/singularity/bcftools_1.15.1--h0ea216a_0.sif"

freebayes:
  "/home/jaykim/jkim/singularity/freebayes_1.3.6--hb089aa1_0.sif"

fastp:
  "/home/jaykim/jkim/singularity/fastp_0.23.2--h79da9fb_0.sif"

tidyverse:
  "/home/jaykim/jkim/singularity/tidyverse_latest.sif"

deepvariant:
  "/home/jaykim/jkim/singularity/deepvariant.sif"

vcftools:
  "/home/jaykim/jkim/singularity/vcftools_v0.1.16-1-deb_cv1.sif"